name: Build APK

on:
  push:
    paths:
      - 'webview-apk-template/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission to Gradlew
        run: chmod +x webview-apk-template/gradlew

      - name: Build APK
        working-directory: webview-apk-template
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webview-apk
          path: webview-apk-template/app/build/outputs/apk/release/app-release.apk
