name: Build APK

on:
  push:
    paths:
      - 'webview-apk-template/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Gradle wrapper jar
        run: |
          mkdir -p webview-apk-template/gradle/wrapper
          curl -sL https://repo1.maven.org/maven2/org/gradle/wrapper/gradle-wrapper/7.6/gradle-wrapper-7.6.jar \
            -o webview-apk-template/gradle/wrapper/gradle-wrapper.jar

      - name: Make wrappers executable
        run: |
          chmod +x webview-apk-template/gradlew
          chmod +x webview-apk-template/gradle/wrapper/gradle-wrapper.jar

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '17'

      - name: Build APK
        working-directory: webview-apk-template
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: webview-apk
          path: app/build/outputs/apk/release/app-release.apk
