name: Build APK

on:
  push:
    paths:
      - 'webview-apk-template/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download working gradle-wrapper.jar
        run: |
          curl -L https://services.gradle.org/distributions/gradle-7.6-bin.zip -o gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip
          mkdir -p webview-apk-template/gradle/wrapper
          cp gradle-7.6/lib/gradle-wrapper.jar webview-apk-template/gradle/wrapper/gradle-wrapper.jar

      - name: Make gradlew executable
        run: chmod +x webview-apk-template/gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build APK
        working-directory: webview-apk-template
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: webview-apk
          path: app/build/outputs/apk/release/app-release.apk
